name: octopus service
realm: "OCTOPUS-SERVICE-AUTH"
jwtSecret: "VERY_PRIVATE_VERY_PRIVATE_VERY_PRIVATE_VERY_PRIVATE_VERY_PRIVATE_VERY_PRIVATE"

database:
  driverClass: org.postgresql.Driver
  user: pg-user
  password: iAMs00perSecrEET
  url: jdbc:postgresql://localhost/db-dev
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8000


sundial:
  thread-pool-size: 10
  shutdown-on-unload: true
  start-delay-seconds: 15
  start-scheduler-on-load: true
  global-lock-on-load: false
  annotated-jobs-package-name: com.octopus.schedulers
